import { test, mock, strict as assert } from 'node:test';
// We test the orchestrator by mocking the Claude CLI bridge so no external calls happen.
import * as cli from '../lib/ai/claude/cli-bridge.mjs';
import { composePR } from '../lib/ai/orchestrator/run.mjs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { promises as fs } from 'node:fs';

test('composePR: applies changes and returns PR info', async () => {
  mock.method(cli, 'runClaudeSession', async () => ({
    changes: [{ path:'README.md', content:'# Hello\n' }],
    pr: { title:'Add README', body:'Generated by agent' }
  }));

  const projectRoot = join(tmpdir(), 'agent-orch-test');
  await fs.mkdir(projectRoot, { recursive: true });
  const res = await composePR({ projectRoot, prompt:'create readme', roster:['node'], ticket:'VIBE-1', onLog:()=>{} });
  assert.equal(res.ok, true);
  assert.ok(res.pr && res.pr.url);
  assert.ok(res.changedFiles.find(p => p === 'README.md'));
});
