name: ci

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: write
  pull-requests: write

jobs:
  test:
    runs-on: self-hosted
    env:
      # Use the built-in Actions token with write permissions.
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      # Pin the destination app repository explicitly (as requested).
      GITHUB_REPO: "amitandale/App-Test"
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "18.20.0"
          cache: "npm"

      - name: Install
        run: npm ci

      - name: Run tests
        run: npm run test

      - name: Coverage (lcov + text)
        run: npm run coverage

      - name: Upload coverage artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: coverage-lcov
          path: ./coverage/lcov.info
          if-no-files-found: ignore
